### ISSUE TITLE
WARN "unsupported" when installing CLI on latest Node LTS (14.17.0) 

### ISSUE THREAD

**Issue by ron-k** [Hoctail/client#3]
`npm WARN notsup Unsupported engine for @hoctail/client@1.3.1: wanted: {"node":">=10 <13"} (current: {"node":"14.17.0","npm":"6.14.13"})`
`npm WARN notsup Not compatible with your version of node/npm: @hoctail/client@1.3.1`

**Comment by pkit** [comment]
fixed in `v1.3.2`
