### ISSUE TITLE
REPL: autocomplete doesn't work correctly after "-"

### ISSUE THREAD

**Issue by ron-k** [Hoctail/client#5]
When typing in a command in REPL having "-", autocomplete doesn't work correctly:
1) Type `.http-c`
2) invoke autocomplete (hit TAB)
Expected: autocomplete suggestion `.http-client-logs`
Actual: autocomplete suggestions:

> case            catch           const           continue child_process   clearImmediate  clearInterval   clearTimeout    cluster         console         crypto constructor

**Comment by pkit** [comment]
fixed in `v1.3.2`
